# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0009_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartManager1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
